### ISSUE TITLE
gamemodes/projectvisualis/schema/vgui/pda/security/cl_overview.lua:76: attempt to call field 'GetZCRollCall' (a nil value)

### ISSUE THREAD

**Issue by Lucasgood5** [ProjectVisualis/BUG-and-Request#43]
```lua
gamemodes/projectvisualis/schema/vgui/pda/security/cl_overview.lua:76: attempt to call field 'GetZCRollCall' (a nil value)
gamemodes/projectvisualis/schema/vgui/pda/security/cl_overview.lua:76 - ()
```

**Comment by Lucasgood5** [comment]
[Autoreport] Error occured from ply STEAM_0:0:139778156 at 7/31/2024, 12:34:20 PM

**Comment by Lucasgood5** [comment]
[Autoreport] Error occured again from ply STEAM_0:0:139778156 at 7/31/2024, 12:50:05 PM

**Comment by Lucasgood5** [comment]
[Autoreport] Error occured again from ply STEAM_0:0:139778156 at 7/31/2024, 12:54:12 PM

**Comment by Lucasgood5** [comment]
[Autoreport] Error occured again from ply STEAM_0:0:139778156 at 7/31/2024, 1:02:45 PM

**Comment by RayVoxYT** [comment]
Fixed CAPITAL letters
